import type { User, Wallet, TestStandard, AssessmentCode, TestResult, DiagnosticCenter, Transaction, ConsentShare } from "@shared/schema";

// Mock current user
export const mockUser: User = {
  id: "user-1",
  email: "adebayo.okonkwo@example.com",
  firstName: "Adebayo",
  lastName: "Okonkwo",
  profileImageUrl: null,
  role: "patient",
  phone: "+234 803 456 7890",
  createdAt: new Date("2024-01-15"),
  updatedAt: new Date("2024-01-15"),
};

// Mock wallet
export const mockWallet: Wallet = {
  id: "wallet-1",
  userId: "user-1",
  balance: "15750.00",
  currency: "NGN",
  createdAt: new Date("2024-01-15"),
  updatedAt: new Date("2024-11-20"),
};

// Mock test standards
export const mockTestStandards: TestStandard[] = [
  {
    id: "test-std-1",
    name: "Comprehensive STI Panel",
    description: "Complete screening for common sexually transmitted infections",
    price: "12500.00",
    currency: "NGN",
    testsIncluded: ["HIV 1&2", "Hepatitis B", "Hepatitis C", "Syphilis", "Gonorrhea", "Chlamydia"],
    sampleType: "Blood & Urine",
    turnaroundTime: "24-48 hours",
    active: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "test-std-2",
    name: "HIV & Hepatitis Screening",
    description: "Essential HIV and hepatitis virus screening",
    price: "7500.00",
    currency: "NGN",
    testsIncluded: ["HIV 1&2 Antibody", "Hepatitis B Surface Antigen", "Hepatitis C Antibody"],
    sampleType: "Blood",
    turnaroundTime: "24 hours",
    active: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "test-std-3",
    name: "Basic STI Check",
    description: "Essential screening for common STIs",
    price: "5000.00",
    currency: "NGN",
    testsIncluded: ["Gonorrhea", "Chlamydia", "Syphilis VDRL"],
    sampleType: "Urine & Blood",
    turnaroundTime: "48 hours",
    active: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

// Mock assessment codes
export const mockAssessmentCodes: AssessmentCode[] = [
  {
    id: "code-1",
    code: "PSN8K2M9L4P7",
    testStandardId: "test-std-1",
    patientId: "user-1",
    patientName: "Adebayo Okonkwo",
    sponsorId: "user-1",
    sponsorType: "self",
    status: "pending",
    validUntil: new Date("2024-12-15"),
    usedAt: null,
    diagnosticCenterId: null,
    createdAt: new Date("2024-11-20"),
  },
  {
    id: "code-2",
    code: "PSN3X7Y2Q9W5",
    testStandardId: "test-std-2",
    patientId: "user-1",
    patientName: "Adebayo Okonkwo",
    sponsorId: "sponsor-1",
    sponsorType: "employer",
    status: "used",
    validUntil: new Date("2024-11-30"),
    usedAt: new Date("2024-11-10"),
    diagnosticCenterId: "center-1",
    createdAt: new Date("2024-10-15"),
  },
];

// Mock diagnostic centers in Lagos, Nigeria
export const mockDiagnosticCenters: DiagnosticCenter[] = [
  {
    id: "center-1",
    userId: "center-user-1",
    name: "Lifebridge Medical Diagnostics",
    address: "12 Admiralty Way, Lekki Phase 1",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    latitude: "6.4474",
    longitude: "3.4649",
    phone: "+234 901 234 5678",
    email: "info@lifebridge.ng",
    hours: "Mon-Fri: 8AM-6PM, Sat: 9AM-2PM",
    verified: true,
    rating: "4.75",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "center-2",
    userId: "center-user-2",
    name: "St. Nicholas Hospital Lab",
    address: "57 Campbell Street, Lagos Island",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    latitude: "6.4550",
    longitude: "3.4242",
    phone: "+234 802 345 6789",
    email: "lab@saintnicholashospital.com",
    hours: "Mon-Sun: 24 Hours",
    verified: true,
    rating: "4.85",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "center-3",
    userId: "center-user-3",
    name: "Clina-Lancet Laboratories",
    address: "21 Mobolaji Bank Anthony Way, Ikeja",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    latitude: "6.6018",
    longitude: "3.3515",
    phone: "+234 703 456 7890",
    email: "contact@clinalancet.com",
    hours: "Mon-Fri: 7AM-7PM, Sat: 8AM-4PM",
    verified: true,
    rating: "4.60",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "center-4",
    userId: "center-user-4",
    name: "Cedarcrest Hospitals Diagnostics",
    address: "8 Oba Elegushi Road, Ikoyi",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    latitude: "6.4541",
    longitude: "3.4366",
    phone: "+234 805 678 9012",
    email: "diagnostics@cedarcrest.com.ng",
    hours: "Mon-Sat: 8AM-5PM",
    verified: true,
    rating: "4.70",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "center-5",
    userId: "center-user-5",
    name: "Pathcare Nigeria",
    address: "Plot 1678 Oladipo Diya Street, Victoria Island",
    city: "Lagos",
    state: "Lagos",
    country: "Nigeria",
    latitude: "6.4281",
    longitude: "3.4219",
    phone: "+234 906 789 0123",
    email: "info@pathcare.ng",
    hours: "Mon-Fri: 7:30AM-6PM, Sat: 8AM-1PM",
    verified: true,
    rating: "4.80",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
];

// Mock test results
export const mockTestResults: TestResult[] = [
  {
    id: "result-1",
    assessmentCodeId: "code-2",
    patientId: "user-1",
    diagnosticCenterId: "center-1",
    testStandardId: "test-std-2",
    results: [
      { parameter: "HIV 1&2 Antibody", value: "Non-Reactive", referenceRange: "Non-Reactive", status: "normal" },
      { parameter: "Hepatitis B Surface Antigen", value: "Negative", referenceRange: "Negative", status: "normal" },
      { parameter: "Hepatitis C Antibody", value: "Negative", referenceRange: "Negative", status: "normal" },
    ],
    viewed: false,
    viewedAt: null,
    sponsorNotified: true,
    sponsorNotifiedAt: new Date("2024-11-12"),
    testedAt: new Date("2024-11-10"),
    uploadedAt: new Date("2024-11-12"),
  },
  {
    id: "result-2",
    assessmentCodeId: "code-prev-1",
    patientId: "user-1",
    diagnosticCenterId: "center-2",
    testStandardId: "test-std-3",
    results: [
      { parameter: "Gonorrhea PCR", value: "Not Detected", referenceRange: "Not Detected", status: "normal" },
      { parameter: "Chlamydia PCR", value: "Not Detected", referenceRange: "Not Detected", status: "normal" },
      { parameter: "Syphilis VDRL", value: "Non-Reactive", referenceRange: "Non-Reactive", status: "normal" },
    ],
    viewed: true,
    viewedAt: new Date("2024-09-16"),
    sponsorNotified: false,
    sponsorNotifiedAt: null,
    testedAt: new Date("2024-09-14"),
    uploadedAt: new Date("2024-09-15"),
  },
];

// Mock transactions
export const mockTransactions: Transaction[] = [
  {
    id: "txn-1",
    walletId: "wallet-1",
    userId: "user-1",
    type: "credit",
    amount: "20000.00",
    currency: "NGN",
    description: "Wallet funding via Card",
    reference: "TXN-20241120-001",
    status: "completed",
    metadata: { method: "card" },
    createdAt: new Date("2024-11-20"),
  },
  {
    id: "txn-2",
    walletId: "wallet-1",
    userId: "user-1",
    type: "debit",
    amount: "12500.00",
    currency: "NGN",
    description: "Purchase: Comprehensive STI Panel",
    reference: "ORD-20241120-001",
    status: "completed",
    metadata: { testStandardId: "test-std-1", codeId: "code-1" },
    createdAt: new Date("2024-11-20"),
  },
  {
    id: "txn-3",
    walletId: "wallet-1",
    userId: "user-1",
    type: "credit",
    amount: "10000.00",
    currency: "NGN",
    description: "Wallet funding via Mobile Money",
    reference: "TXN-20241015-002",
    status: "completed",
    metadata: { method: "mobile" },
    createdAt: new Date("2024-10-15"),
  },
];

// Mock consent shares
export const mockConsentShares: ConsentShare[] = [
  {
    id: "share-1",
    testResultId: "result-2",
    patientId: "user-1",
    sharedWith: "dr.amina@healthclinic.ng",
    sharedWithType: "email",
    accessLevel: "full",
    expiresAt: new Date("2024-12-14"),
    revoked: false,
    revokedAt: null,
    accessedAt: new Date("2024-09-17"),
    createdAt: new Date("2024-09-16"),
  },
];

// Mock sponsor data
export const mockSponsoredCodes = [
  {
    id: "sponsored-1",
    recipientName: "Chioma Nwosu",
    recipientContact: "+234 803 456 7890",
    testType: "Comprehensive STI Panel",
    code: "PSN3X7Y2Q9W5",
    status: "completed" as const,
    sentAt: new Date("2024-11-05"),
    completedAt: new Date("2024-11-10"),
  },
  {
    id: "sponsored-2",
    recipientName: "Oluwaseun Adeyemi",
    recipientContact: "+234 805 678 9012",
    testType: "HIV & Hepatitis Screening",
    code: "PSN2M8K4N7L3",
    status: "pending" as const,
    sentAt: new Date("2024-11-15"),
    completedAt: undefined,
  },
];

// Mock diagnostic center data
export const mockCenterTests = [
  {
    id: "test-1",
    code: "PSN3X7Y2Q9W5",
    patientName: "Adebayo Okonkwo",
    testType: "HIV & Hepatitis Screening",
    status: "completed" as const,
    testedAt: new Date("2024-11-10"),
  },
  {
    id: "test-2",
    code: "PSN2M8K4N7L3",
    patientName: "Chioma Nwosu",
    testType: "Comprehensive STI Panel",
    status: "completed" as const,
    testedAt: new Date("2024-11-08"),
  },
];

// Mock code validation data
export const mockCodeValidation = {
  code: "PSN8K2M9L4P7",
  patientName: "Adebayo Okonkwo",
  testType: "Comprehensive STI Panel",
  testsIncluded: ["HIV 1&2", "Hepatitis B", "Hepatitis C", "Syphilis", "Gonorrhea", "Chlamydia"],
  sponsorType: "Self-Paid",
  validUntil: new Date("2024-12-15"),
  status: "Valid",
};
